name: Lint Python with Ruff

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Set up uv
        uses: astral-sh/setup-uv@main

      - name: Run lint via ruff check
        run: make lint

