name: Build MicroPythonOS for ESP32-S3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: astral-sh/setup-uv@main
      - run: uv tool run ruff check .

  build:
    needs: lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install esp-idf dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential libffi-dev pkg-config cmake ninja-build

      - name: Extract version
        id: version
        run: |
          OS_VERSION=$(grep "release = " internal_filesystem/lib/mpos/build_info.py | cut -d "=" -f 2 | cut -d "#" -f 1 | tr -d " " | tr -d '"')
          echo "OS_VERSION=$OS_VERSION" >> $GITHUB_OUTPUT

      - name: Build esp32s3 firmware
        run: |
          ./scripts/build_mpos.sh esp32s3
          mv lvgl_micropython/build/lvgl_micropy_ESP32_GENERIC_S3-SPIRAM_OCT-16.bin lvgl_micropython/build/MicroPythonOS_esp32s3_${{ steps.version.outputs.OS_VERSION }}.bin
          mv lvgl_micropython/lib/micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/micropython.bin lvgl_micropython/lib/micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/MicroPythonOS_esp32s3_${{ steps.version.outputs.OS_VERSION }}.ota

      - name: Upload firmware binary
        uses: actions/upload-artifact@v4
        with:
          name: MicroPythonOS_esp32s3_${{ steps.version.outputs.OS_VERSION }}.bin
          path: lvgl_micropython/build/MicroPythonOS_esp32s3_${{ steps.version.outputs.OS_VERSION }}.bin
          retention-days: 7

      - name: Upload OTA update
        uses: actions/upload-artifact@v4
        with:
          name: MicroPythonOS_esp32s3_${{ steps.version.outputs.OS_VERSION }}.ota
          path: lvgl_micropython/lib/micropython/ports/esp32/build-ESP32_GENERIC_S3-SPIRAM_OCT/MicroPythonOS_esp32s3_${{ steps.version.outputs.OS_VERSION }}.ota
          retention-days: 7
