name: Build LVGL MicroPython for macOS Intel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # allow manual workflow starts

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-15-intel
    timeout-minutes: 60
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_ANALYTICS: 1

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Install dependencies via Homebrew
        run: |
          xcode-select --install || true # already installed on github
          brew install pkg-config libffi ninja make SDL2

      - name: Show version numbers
        run: |
          xcodebuild -version
          clang --version

      - name: Extract OS version
        id: version
        run: |
            OS_VERSION=$(grep "release = " internal_filesystem/lib/mpos/build_info.py | cut -d "=" -f 2 | cut -d "#" -f 1 | tr -d " " | tr -d '"')
            echo "OS_VERSION=$OS_VERSION" >> $GITHUB_OUTPUT
            echo "Extracted version: $OS_VERSION"

      - name: Build LVGL MicroPython for macOS dev
        run: |
          ./scripts/build_mpos.sh macOS
          cp lvgl_micropython/build/lvgl_micropy_macOS lvgl_micropython/build/MicroPythonOS_intel_macOS_${{ steps.version.outputs.OS_VERSION }}.bin

      - name: Upload built binary as artifact
        uses: actions/upload-artifact@v7
        with:
          name: MicroPythonOS_intel_macOS_${{ steps.version.outputs.OS_VERSION }}.bin
          path: lvgl_micropython/build/MicroPythonOS_intel_macOS_${{ steps.version.outputs.OS_VERSION }}.bin
          retention-days: 7

      - name: Run syntax tests on macOS
        run: |
          ./tests/syntax.sh

      - name: Run unit tests on macOS
        run: |
          ./scripts/test_runner.py
