name: Build LVGL MicroPython on Push to add-submodules

on:
  push:
    branches:
      - add-submodules

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu is Debian-based and commonly used in GitHub Actions

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fetch tags, needed for lib/SDL
        run: |
          git submodule foreach --recursive 'git fetch origin "refs/*:refs/*"'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libffi-dev \
            pkg-config \
            cmake \
            ninja-build \
            gnome-desktop-testing \
            libasound2-dev \
            libpulse-dev \
            libaudio-dev \
            libjack-dev \
            libsndio-dev \
            libx11-dev \
            libxext-dev \
            libxrandr-dev \
            libxcursor-dev \
            libxfixes-dev \
            libxi-dev \
            libxss-dev \
            libxkbcommon-dev \
            libdrm-dev \
            libgbm-dev \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            libegl1-mesa-dev \
            libdbus-1-dev \
            libibus-1.0-dev \
            libudev-dev \
            fcitx-libs-dev \
            libpipewire-0.3-dev \
            libwayland-dev \
            libdecor-0-dev \
            git

      - name: Build LVGL MicroPython
        run: |
          ./scripts/build_lvgl_micropython.sh unix dev

      - name: Upload built binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: lvgl_micropy_unix
          path: lvgl_micropython/build/lvgl_micropy_unix
          retention-days: 7  # Adjust as needed; artifacts can be downloaded from the workflow run summary
